# For MinGW32 environment
# syntax: 'make -fmakefile.w32'

CC=g++
CFLAGS=-s -O2 -o glinfo
LFLAGS=-lopengl32 -lglew32 -lfreeglut

all: main.cpp
	$(CC) main.cpp $(CFLAGS) $(LFLAGS)

clean:
	del glinfo.exe

